version: '3'
services:
  fluentd:
    image: fluent/fluentd
    command:
      - "fluentd"
      - "-v"
      - "-p"
      - "/fluentd/plugins"
    volumes:
      - ./conf:/fluentd/etc
      - ../lib/fluent/plugin:/fluentd/plugins
      - /var/log:/var/log
    environment:
      LOKI_USERNAME:
      LOKI_PASSWORD:
      FLUENT_CONF: /fluentd/etc/fluentd-2.conf
      FLUENT_UID: '0'
